
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import "primereact/resources/themes/lara-light-cyan/theme.css";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('abc')
  return (
    <html lang="en">
    <head>
      <title>Documentation</title>
    </head>
    <body>
    <div className='main'>
      <div className='gradient' />
    </div>
    <main className='app'>
      <Navigation />
      {children}
    </main>
    </body>
    </html>
  )
}
